name: melonDS Android PlayStore Release

# 仅手动触发
on:
  workflow_dispatch:

jobs:
  playstore-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 不再做 keystore 解码、签名密码注入;签名放到 mt 工具手动完成
      - name: Build melonDS Android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assemblePlayStoreProdRelease

      - name: Get Version
        id: release_params
        run: echo VERSION=$(grep -oP 'versionName = "\K(.*?)(?=")' buildSrc/src/main/kotlin/AppConfig.kt) >> $GITHUB_OUTPUT

      - name: Create Play Store Release
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.MELONDS_PLAYSTORE_ACCOUNT_JSON }}
          packageName: me.magnum.melonds
          releaseName: ${{ steps.release_params.outputs.VERSION }}
          releaseFiles: app/build/outputs/apk/playStoreProd/release/app-playStore-prod-release.apk
          track: production
          inAppUpdatePriority: 2
          status: draft
          whatsNewDirectory: ./.github/changelog/playStore
          mappingFile: app/build/outputs/mapping/playStoreProdRelease/mapping.txt
          debugSymbols: app/build/outputs/native-debug-symbols/playStoreProdRelease/native-debug-symbols.zip

      - name: Upload APK, Mapping and Debug Symbols
        uses: actions/upload-artifact@v4
        with:
          name: playstore-release
          path: |
            app/build/outputs/apk/playStoreProd/release/app-playStore-prod-release.apk
            app/build/outputs/mapping/playStoreProdRelease/mapping.txt
            app/build/outputs/native-debug-symbols/playStoreProdRelease/native-debug-symbols.zip